//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sigma.rc
//
#define IDR_MAINFRAME_TOOLBAR           109
#define IDR_MAINFRAME                   110
#define IDR_DOCTYPE_DATA                111
#define IDR_DOCTYPE_PLOT                112
#define IDI_SCRIPT                      113
#define IDI_CONSOLE                     114
#define IDI_PARAM                       115
#define IDI_OUTPUT                      116
#define IDI_NOTE                        117
#define IDI_FITTER                      118
#define IDI_IMPORT                      119
#define IDI_FORMULA                     120
#define IDI_TEXT                        121
#define IDI_LINE                        122
#define IDI_INPUT                       123
#define IDI_RECT                        124
#define IDD_VARLIST                     131
#define IDD_ABOUTBOX                    140
#define IDD_PLOTOPT_CURVE               145
#define IDD_PLOTOPT_AXES                146
#define IDD_PLOTOPT_LINE                147
#define IDD_PLOTOPT_SCALE               148
#define IDD_PLOTOPT_GENERAL             149
#define IDD_CONSOLE                     164
#define IDD_IMPORT                      180
#define IDR_SIGMATYPE                   200
#define IDM_CONSOLE                     202
#define IDM_CONSOLE_POP                 203
#define IDM_PLOTPOP_MAIN                204
#define IDR_TOOLBAR_DATA                207
#define IDR_TOOLBAR_PLOT                212
#define IDR_TOOLBAR_SCRIPT              213
#define IDD_OUTPUT                      231
#define IDD_NOTE                        232
#define IDD_COLUMN                      233
#define IDB_FITTER_MODEL01              240
#define IDB_FITTER_MODEL02              241
#define IDB_FITTER_MODEL03              242
#define IDB_FITTER_MODEL04              243
#define IDB_FITTER_MODEL05              244
#define IDB_FITTER_MODEL06              245
#define IDB_FITTER_MODEL07              246
#define IDB_FITTER_MODEL08              247
#define IDB_FITTER_MODEL09              248
#define IDB_FITTER_MODEL10              249
#define IDB_FITTER_MODEL11              250
#define IDB_FITTER_MODEL12              253
#define IDB_FITTER_MODEL13              254
#define IDB_FITTER_MODEL14              255
#define IDB_FITTER_MODEL15              256
#define IDB_FITTER_MODEL16              257
#define IDB_FITTER_MODEL17              258
#define IDB_FITTER_MODEL18              259
#define IDB_FITTER_MODEL19              260
#define IDB_FITTER_MODEL20              261
#define IDB_FITTER_MODEL21              262
#define IDB_FITTER_MODEL22              263
#define IDB_FITTER_MODEL23              264
#define IDB_FITTER_MODEL24              265
#define IDB_FITTER_MODEL99              279
#define IDB_ARROW_STYLE00               281
#define IDB_ARROW_STYLE01               282
#define IDB_FITTER_MODEL100             283
#define IDB_FITTER_MODEL255             284
#define IDB_TOOLBAR_FILE                286
#define IDB_TOOLBAR_DATA                287
#define IDB_TOOLBAR_PLOT                288
#define IDB_TOOLBAR_SCRIPT              289
#define IDM_DATAPOP_COLUMN              301
#define IDD_STATS                       302
#define IDM_FORMULA                     303
#define IDD_FITTER_MODEL                305
#define IDD_FITTER_FILTER               306
#define IDM_DATAPOP_ROW                 307
#define IDM_DATAPOP_CELL                308
#define IDD_SERIES                      309
#define IDD_TEXT                        310
#define IDD_FORMULA                     312
#define IDD_ADDCURVE                    314
#define IDD_INPUT_TEXT                  317
#define IDD_INPUT_REAL                  318
#define IDD_GEOMETRIC_LINE              320
#define IDD_GEOMETRIC_RECT              322
#define IDM_PLOTPOP_ITEM                323
#define IDD_IMPORT_DROP                 324
#define IDM_PLOTPOP_CURVE               325
#define IDD_FITTER_REPORT               326
#define IDM_DATAPOP_CELL_RO             327
#define IDD_FITTER_OPTIONS              328
#define IDM_DATAPOP_COLUMN_RO           329
#define IDD_ERRORBAR                    330
#define IDM_DATAPOP_ROW_RO              331
#define IDD_NUMPAD                      332
#define IDM_DATAPOP                     333
#define IDD_MATH                        334
#define IDD_SCRIPT                      335
#define IDD_SCRIPT_FAVORITE             336
#define IDM_OUTPUTPOP                   337
#define IDD_TEMPLATES                   338
#define IDM_PLOTPOP                     339
#define IDD_INPUT_VARIABLE              341
#define IDD_INPUT_VARSET                342
#define IDM_DATAPOP_MAIN                343
#define IDM_SCRIPT                      345
#define IDD_FITTER_USERMODEL            346
#define IDD_SCRIPT_COLORS                397
#define IDD_SCINTILLA_FINDDLGORD        398
#define IDD_SCINTILLA_REPLACEDLGORD     399
#define IDE_SCRIPT                        500
#define ID_CLEAR_RECENTFILELIST         511
#define IDC_HOLDER1                     1002
#define IDC_HOLDER2                     1003
#define IDC_HOLDER3                     1004
#define IDL_VARLIST                     1007
#define ID_VARLIST_REFRESH              1008
#define ID_VARLIST_SET                  1009
#define ID_VARLIST_UNSET                1010
#define IDAPPLY                         1015
#define IDE_CONSOLE                     1020
#define IDS_CURVE                       1100
#define IDC_CURVE_LINESIZE              1103
#define IDF_CURVE_DOTSTYLE              1104
#define IDC_CURVE_CONNECT               1105
#define IDC_CURVE_DROPSIZE              1106
#define IDC_CURVE_DOTSIZE               1107
#define IDF_CURVE_DROPSTYLE             1108
#define IDF_CURVE_DROPSTYLEH            1109
#define IDF_CURVE_LINESTYLE             1110
#define IDE_CURVE_LEGEND                1111
#define IDF_CURVE_CONNECTSTYLE          1112
#define IDC_CURVE_DROPSIZEH             1113
#define IDC_CURVE                       1114
#define IDE_XTITLE                      1120
#define IDE_PLOTYGRID                   1121
#define IDE_YTITLE                      1122
#define IDE_PLOTXMIN                    1123
#define IDE_AXIS_MIN                    1124
#define IDE_PLOTYGRIDM                  1125
#define IDE_PLOTXMAX                    1126
#define IDE_AXIS_MAX                    1127
#define IDE_PLOTYMIN                    1128
#define IDE_PLOTZMIN                    1129
#define IDE_PLOTYMAX                    1130
#define IDE_PLOTZMAX                    1131
#define IDK_PLOTYGRID                   1132
#define IDK_PLOTYGRIDM                  1133
#define IDK_PLOTYTICKM                  1134
#define IDK_TOP                         1136
#define IDK_TOPAXIS                     1137
#define IDK_PLOTYTICK                   1141
#define IDK_RIGHT                       1142
#define IDK_RIGHTAXIS                   1143
#define IDF_INSIDE                      1147
#define IDS_STATIC                      1148
#define IDE_CURVE                       1151
#define ID_CURVE_DELETE                 1157
#define ID_CURVE_HIDE                   1158
#define ID_CURVE_REMOVE                 1159
#define ID_CURVE_ACTIVE                 1160
#define IDE_AXIS_TITLE                  1181
#define ID_AXISTCOLOR                   1182
#define ID_AXIS_TFONT                   1183
#define ID_AXISCOLOR                    1184
#define ID_AXIS_LFONT                   1185
#define ID_LABELFONT                    1186
#define ID_AXISGCOLOR                   1189
#define ID_AXISGCOLORM                  1190
#define IDE_AXISGRIDM                   1191
#define IDE_AXISGRID                    1192
#define ID_AXISTCOLORM                  1196
#define ID_AXISTTCOLOR                  1200
#define IDE_AXIS_SIZE                   1206
#define IDE_TITLE                       1211
#define ID_FONTCHOOSE                   1212
#define IDK_OTITLE                      1213
#define IDK_AXIS_STATUS                 1215
#define IDK_AXIS_OTITLE                 1216
#define IDK_AXIS_OTICK                  1217
#define IDK_AXIS_TOP                    1218
#define IDK_AXIS_RIGHT                  1219
#define IDK_AXIS_OLABEL                 1220
#define IDK_AXIS_OTICKM                 1221
#define IDC_AXIS_FONTCOLOR              1222
#define IDC_PLOT_COLOR                  1223
#define IDC_PLOT_COLORB                 1224
#define IDC_AXIS_COLOR                  1225
#define IDC_AXIS_LABELCOLOR             1226
#define IDC_AXIS_GRIDCOLOR              1227
#define IDC_AXIS_GRIDMCOLOR             1228
#define ID_AXIS_APPLYALL                1229
#define ID_AXIS_APPLY                   1230
#define IDK_CURVE_LEGEND                1231
#define IDC_CURVE_LINECOLOR             1232
#define IDC_CURVE_LINESTYLE             1233
#define IDC_CURVE_DROPVSTYLE            1234
#define IDC_CURVE_DROPHSTYLE            1235
#define IDK_CURVE_DROPVERT              1236
#define IDC_CURVE_DOTSTYLE              1237
#define IDC_CURVE_CONNECTSTYLE          1238
#define IDC_CURVE_DROPCOLOR             1239
#define IDC_CURVE_DOTCOLOR              1240
#define IDC_CURVE_DROPCOLORH            1241
#define ID_CURVE_APPLYALL               1243
#define ID_CURVE_DEFAULT                1244
#define IDK_AXISLINK                    1245
#define IDK_AUTOSCALE                   1246
#define ID_PLOT_DEFAULT                 1268
#define IDP_PROGRESS                    1280
#define IDL_PROGRESS                    1281
#define IDF_PICKER_A                    1282
#define IDF_PICKER_B                    1283
#define IDF_PICKER_C                    1284
#define IDF_PICKER_D                    1285
#define IDF_PICKER_E                    1286
#define IDF_PICKER_F                    1287
#define IDF_PICKER_G                    1288
#define IDF_PICKER_H                    1289
#define IDF_PICKER_I                    1290
#define IDF_PICKER_J                    1291
#define IDF_PICKER_K                    1292
#define IDF_PICKER_L                    1293
#define IDF_PICKER_M                    1294
#define IDF_PICKER_N                    1295
#define IDF_PICKER_O                    1296
#define IDF_PICKER_P                    1297
#define IDF_PICKER_Q                    1298
#define IDF_PICKER_R                    1299
#define IDF_PICKER_S                    1300
#define IDF_PICKER_T                    1301
#define ID_XTFONT                       1304
#define ID_YTFONT                       1305
#define ID_PLOTBCOLOR                   1306
#define ID_PLOTPBCOLOR                  1307
#define ID_PLOTFCOLOR                   1308
#define ID_PLOTYGCOLOR                  1309
#define ID_PLOTYTCOLOR                  1310
#define ID_PLOTYGCOLORM                 1311
#define ID_PLOTYTCOLORM                 1312
#define IDC_CURVE_COLOR                 1313
#define IDC_CURVESCOLOR                 1314
#define IDC_CURVEDCOLOR                 1315
#define IDL_NEWLIST                     1320
#define IDC_AXIS_FORMAT                 1330
#define IDO_AXIS_LINEAR                 1332
#define IDO_AXIS_LOG                    1333
#define IDO_AXIS_LEFT                   1336
#define IDO_AXIS_TOP                    1337
#define IDO_AXIS_RIGHT                  1338
#define IDO_AXIS_BOTTOM                 1339
#define IDE_AXIS_PREFIX                 1345
#define IDE_AXIS_SUFFIX                 1346
#define ID_PLOTTER_ADD                  1360
#define ID_PLOTTER_REM                  1361
#define ID_PLOTTER_HIDE                 1362
#define ID_PLOTTER_OK                   1363
#define ID_PLOTTER_CANCEL               1364
#define IDL_PLOTTER_CURVES              1365
#define ID_PLOT_ADDTEXT                 1390
#define IDE_NOTE                        1391
#define IDC_PARAM_ITEM                  1400
#define IDC_PARAM_TYPE                  1401
#define IDC_PARAM_MATERIAL              1402
#define IDC_PARAM_NV                    1420
#define IDC_PARAM_NC                    1421
#define IDL_SAVELIST                    1452
#define IDL_EXPORTLIST                  1453
#define IDS_AXIS_SIZE                   1454
#define ID_GENERAL_DEFAULT              1480
#define IDK_AXIS_OGRID                  1481
#define ID_SCALE_DEFAULT                1483
#define IDK_AXIS_OGRIDM                 1485
#define IDE_AXIS_GRIDCOUNT              1487
#define IDE_AXIS_GRIDMCOUNT             1488
#define ID_SCALE_AUTO                   1489
#define IDE_OUTPUT                      1531
#define IDO_IMPORT_TAB                  1564
#define IDE_FITTER_MAXX                 1580
#define IDE_FITTER_MINX                 1581
#define IDE_FITTER_PARA                 1582
#define IDE_FITTER_PARB                 1583
#define IDE_FITTER_PARC                 1584
#define IDE_FITTER_PARD                 1585
#define IDE_FITTER_PARE                 1586
#define IDE_FITTER_PARF                 1587
#define IDE_FITTER_ITER                 1588
#define IDK_FITTER_MASK                 1589
#define IDE_FITTER_TOL                  1590
#define IDK_FITTER_SCI                  1591
#define IDE_FITTER_RELTOL               1592
#define IDK_FITTER_FIXEDA               1593
#define IDK_FITTER_FIXEDB               1594
#define IDK_FITTER_FIXEDC               1595
#define IDK_FITTER_FIXEDD               1596
#define IDK_FITTER_FIXEDE               1597
#define IDK_FITTER_FIXEDF               1598
#define IDE_FITTER_CHI2                 1599
#define IDK_FITTER_FILTER               1601
#define IDE_FITTER_BASELINE0            1602
#define IDE_FITTER_BASELINE1            1603
#define IDE_FITTER_FILTER               1604
#define IDC_FITTER_PROGRESS             1605
#define ID_FITTER_NEXTPAR               1606
#define IDK_FITTER_BASELINE             1612
#define IDK_FITTER_ORGAPPLY             1613
#define IDK_FITTER_ORGAPPLYMASK         1614
#define IDE_FITTER_OUT                  1615
#define IDE_FITTER_DATA                 1616
#define IDO_FITTER_NEWPLOT              1617
#define IDO_FITTER_ADDPLOT              1618
#define IDE_FITTER_CX                   1619
#define IDE_FITTER_CY                   1620
#define ID_FITTER_AUTOPAR               1621
#define ID_FITTER_PROCESS               1622
#define ID_FITTER_FIT                   1623
#define IDC_FITTER_TOL                  1624
#define IDF_FITTER_MODEL                1626
#define IDL_FITTER_MODEL                1627
#define ID_FITTER_TRANSLATEH            1628
#define ID_FITTER_TRANSLATEV            1629
#define ID_FITTER_STATS                 1630
#define IDE_FITTER_POINTS               1631
#define IDE_FITTER_NPOINTS              1632
#define ID_FITTER_RESET                 1633
#define IDL_FITTER_PARA                 1634
#define IDL_FITTER_PARB                 1635
#define IDL_FITTER_PARC                 1636
#define IDL_FITTER_PARD                 1637
#define IDK_FITTER_SHOWPEAKS            1638
#define IDL_FITTER_PARTITLE             1640
#define IDE_STATS_POINTS                1641
#define IDE_STATS_MIN                   1642
#define IDE_STATS_MAX                   1643
#define IDE_STATS_SUM                   1644
#define IDE_STATS_MEAN                  1645
#define IDE_STATS_MEDIAN                1646
#define IDE_STATS_RMS                   1647
#define IDE_STATS_STDDEV                1648
#define IDE_STATS_VAR                   1649
#define IDE_STATS_COEFF                 1650
#define IDE_STATS_SKEW                  1651
#define IDE_STATS_KURT                  1652
#define IDL_STATS_COMMENT               1654
#define IDT_EXPLORER                    1655
#define IDE_ASCII_CONTENT               1670
#define IDE_ASCII_FILENAME              1671
#define IDE_ASCII_FILEINFO              1672
#define IDC_ASCII_SEP                   1673
#define IDE_ASCII_SEP                   1674
#define IDE_ASCII_SKIP                  1675
#define IDE_ASCII_COLX                  1676
#define IDE_ASCII_COLY                  1677
#define IDO_ASCII_DADD                  1678
#define IDL_ASCII_DATASHEET             1679
#define IDO_ASCII_DNEW                  1680
#define IDE_ASCII_ROWCOUNT              1681
#define IDE_ASCII_ROW                   1682
#define ID_ASCII_OK                     1683
#define ID_ASCII_CANCEL                 1684
#define IDK_ASCII_DDEF                  1685
#define ID_ASCII_BROWSE                 1687
#define IDE_ASCII_SELCOLS               1688
#define IDC_STATS_DATA                  1689
#define ID_INDICATOR_LINE               1690
#define ID_INDICATOR_AA                 1692
#define ID_INDICATOR_BB                 1693
#define ID_INDICATOR_ANGLEUNIT          1694
#define ID_INDICATOR_PAR                1695
#define IDC_FITTER_MODEL                1696
#define IDE_SERIES_FROM                 1697
#define IDE_SERIES_TO                   1698
#define IDE_SERIES_INCREMENT            1699
#define IDE_SERIES_MULTIPLIER           1700
#define ID_UNDO                         1701
#define IDCOPY                          1702
#define IDL_INPUT                       1707
#define IDE_INPUT                       1708
#define IDL_INPUT2                      1709
#define IDE_INPUT2                      1710
#define IDE_INPUT1                      1711
#define IDL_INPUT1                      1712
#define IDC_COLUMN_FORMAT               1713
#define IDE_COLUMN_PREFIX               1714
#define IDE_COLUMN_SUFFIX               1715
#define IDE_COLUMN_LABEL                1716
#define IDO_COLUMN_SHOWNAME             1717
#define IDO_COLUMN_SHOWLABEL            1718
#define IDO_COLUMN_SHOWBOTH             1719
#define IDL_FORMULA                     1720
#define IDE_FORMULA                     1721
#define IDE_ROW_FROM                    1722
#define IDE_ROW_TO                      1723
#define IDL_COLUMN_X                    1724
#define IDO_COLUMN_X                    1725
#define IDO_COLUMN_Y                    1726
#define IDO_COLUMN_BARX                 1727
#define IDL_COLUMN_Y                    1728
#define IDO_COLUMN_BARY                 1729
#define ID_CURVE_ADD                    1730
#define ID_INPUT_FONTCHOOSE             1731
#define IDC_INPUT_FONTCOLOR             1734
#define IDO_TEXT_ORIENT00               1735
#define IDO_TEXT_ORIENT90               1736
#define IDO_TEXT_ORIENT270              1737
#define IDB_PLOT_PREVIEW                1741
#define IDC_FILL_COLOR                  1747
#define ID_CURVE_FONT                   1750
#define IDO_ARROW_BEGIN                 1753
#define IDO_ARROW_END                   1754
#define IDO_ARROW_BOTH                  1755
#define IDO_ARROW_STYLE00               1756
#define IDO_ARROW_STYLE01               1757
#define IDO_ARROW_NONE                  1758
#define IDF_LINE_STYLE                  1759
#define IDC_LINE_SIZE                   1760
#define IDC_LINE_COLOR                  1761
#define IDK_FILL                        1762
#define IDK_SERIES_TO                   1763
#define IDK_ASCII_SELCOL                1764
#define IDK_ASCII_READTITLE             1765
#define IDL_ADDCURVE_OUTPUT             1768
#define IDS_COLUMN_CURRENT              1769
#define IDS_FITREPORT_CURVE             1771
#define IDE_FITREPORT                   1772
#define IDE_ERRBAR_PERCENT              1773
#define IDE_ERRBAR_FIXED                1774
#define IDE_FITTER_LAMBDA               1775
#define IDK_FITTER_REPORT               1777
#define IDL_FITTER_OUTPUT               1778
#define ID_FITTER_UNDO                  1779
#define IDO_ERRBAR_X                    1780
#define IDO_ERRBAR_Y                    1781
#define IDO_ERRBAR_PERCENT              1782
#define IDO_ERRBAR_FIXED                1783
#define IDO_ERRBAR_COLUMNX              1784
#define IDC_ERRBAR_COLUMNX              1785
#define IDF_ERRBAR_LINESTYLE            1786
#define IDC_ERRBAR_LINESIZE             1787
#define IDC_ERRBAR_LINECOLOR            1788
#define IDO_ERRBAR_COLUMNY              1789
#define IDC_ERRBAR_COLUMNY              1790
#define IDO_ERRBAR_STYLE                1791
#define ID_ERRBAR_REMOVE                1792
#define ID_INPUT_SEVEN                  1812
#define ID_INPUT_EIGHT                  1814
#define ID_INPUT_NINE                   1815
#define ID_INPUT_FOUR                   1816
#define ID_INPUT_FIVE                   1817
#define ID_INPUT_SIX                    1818
#define ID_INPUT_ONE                    1819
#define ID_INPUT_TWO                    1820
#define ID_INPUT_THREE                  1821
#define ID_INPUT_DIV                    1822
#define ID_INPUT_MULT                   1823
#define ID_INPUT_MINUS                  1824
#define ID_INPUT_ZERO                   1825
#define ID_INPUT_DOT                    1827
#define ID_INPUT_PLUS                   1828
#define ID_INPUT_PARENTH1               1829
#define ID_INPUT_PARENTH2               1830
#define ID_INPUT_EXP                    1831
#define ID_INPUT_EQUAL                  1832
#define ID_INPUT_BACK                   1833
#define IDL_RIGHT                       1843
#define IDK_AXIS_ABS                    1844
#define IDE_SCRIPT_INPUT                1846
#define IDO_CURVE_AXISXY                1849
#define IDO_CURVE_AXISXY2               1850
#define IDO_CURVE_AXISX2Y               1851
#define IDO_CURVE_AXISX2Y2              1852
#define IDL_ANALYSIS_INPUT              1871
#define IDL_ANALYSIS_OUTPUT             1872
#define ID_ANALYSIS_CALC                1873
#define IDK_ANALYSIS_ADDCURVE           1874
#define IDK_ANALYSIS_NEWCOLUMN          1875
#define IDC_ANALYSIS_OPERATION          1876
#define IDE_ANALYSIS_OUTPUT             1877
#define IDK_ANALYSIS_FFTSHIFT           1878
#define IDL_ANALYSIS_AVG                1880
#define IDS_ANALYSIS_AVG                1881
#define ID_SCRIPT_ADDFAV                1882
#define ID_SCRIPT_REMFAV                1883
#define ID_SCRIPT_LOADFAV               1884
#define IDL_SCRIPT_FAVORITE             1885
#define ID_SCRIPT_UPFAV                 1886
#define ID_SCRIPT_DOWNFAV               1887
#define IDL_FAV_OUTPUT                  1888
#define IDK_SCRIPT_AUTOLOAD             1889
#define IDK_SCRIPT_AUTORUN              1890
#define IDE_LINE_POS                    1892
#define IDE_LINE_MIN                    1893
#define IDE_LINE_MAX                    1894
#define IDC_LINE                        1895
#define IDO_LINE_HORZ                   1896
#define IDO_LINE_VERT                   1897
#define ID_LINE_HIDE                    1898
#define ID_LINE_REMOVE                  1899
#define ID_LINE_DEFAULT                 1900
#define ID_LINE_ADD                     1902
#define ID_LINE_APPLYALL                1903
#define IDE_MODPOINTS                   1908
#define IDE_AXIS_LINK                   1909
#define IDL_AXIS_LINK                   1910
#define IDC_LINE_STYLE                  1912
#define IDC_DOT_STYLE                   1913
#define ID_TEMPLATE_APPLY               1915
#define ID_TEMPLATE_ADD                 1916
#define ID_TEMPLATE_REMOVE              1917
#define ID_TEMPLATE_EDIT                1918
#define IDK_TEMPLATE_DEFAULT            1920
#define IDL_TEMPLATE_LIST               1922
#define IDF_TEMPLATE_PLOT               1923
#define IDC_TITLE_FONTCOLOR             1924
#define IDE_INPUT_NAME                  1925
#define IDE_INPUT_VALUE                 1926
#define IDS_USERMODEL_PARAMCOUNT        1940
#define IDE_USERMODEL_PARAMCOUNT        1941
#define IDE_USERMODEL_NAME              1942
#define ID_USERMODEL_ADD                1943
#define ID_USERMODEL_REMOVE             1944
#define ID_USERMODEL_UPDATE             1945
#define IDC_USERMODEL_LIST              1946
#define IDE_USERMODEL_FUNCTION          1947
#define ID_USERMODEL_EDIT               1948
#define IDE_USERMODEL_DERIVATIVE        1949
#define IDC_USERMODEL_DERIVATIVE        1950
#define IDL_USERMODEL_PARAMCOUNT        1951
#define IDK_USERMODEL                   1952
#define ID_PARSER_FUNC10                2310
#define ID_PARSER_FUNC01                2311
#define ID_PARSER_FUNC02                2312
#define ID_PARSER_FUNC03                2313
#define ID_PARSER_FUNC04                2314
#define ID_PARSER_FUNC05                2315
#define ID_PARSER_FUNC06                2316
#define ID_PARSER_FUNC11                2321
#define ID_PARSER_FUNC12                2322
#define ID_PARSER_FUNC20                2330
#define ID_PARSER_FUNC30                2331
#define ID_PARSER_FUNC80                2390
#define ID_PARSER_FUNC81                2391
#define ID_PARSER_FUNC82                2392
#define ID_PARSER_FUNC83                2393
#define ID_PARSER_FUNC84                2394
#define ID_PARSER_CONST01               2401
#define ID_PARSER_CONST02               2402
#define ID_CONSOLE_OPT01                2440
#define ID_CONSOLE_TOPMOST              2442
#define ID_CONSOLE_SAVEAS               2449
#define ID_CONSOLE_OPEN                 2450
#define ID_CONSOLE_FIND                 2451
#define ID_CONSOLE_FINDAGAIN            2452
#define ID_CONSOLE_CLOSE                2453
#define ID_CONSOLE_KEYPAD               2454
#define ID_PARSER_CONST                 2460
#define ID_PARSER_CONST10               2461
#define ID_PARSER_CONST11               2462
#define ID_PARSER_CONST12               2463
#define ID_PARSER_CONST13               2464
#define ID_PARSER_CONST14               2465
#define ID_PARSER_CONST15               2466
#define ID_PARSER_CONST16               2467
#define ID_CONSOLE_CLEAR                2470
#define ID_CONSOLE_RESET                2471
#define ID_PARSER_RAD                   2472
#define ID_PARSER_DEG                   2473
#define ID_PARSER_GRAD                  2474
#define ID_CONSOLE_FONT                 2475
#define ID_CONSOLE_FONTCOLOR            2476
#define ID_OPTIONS_GRAD                 2480
#define ID_CONSOLE_CUT                  2480
#define ID_CONSOLE_POPRESET             2481
#define ID_CONSOLE_POPSAVEAS            2482
#define ID_CONSOLE_POPOPEN              2483
#define ID_CONSOLE_POPRAD               2484
#define ID_CONSOLE_POPDEG               2485
#define ID_CONSOLE_POPGRAD              2486
#define ID_CONSOLE_POPFONT              2487
#define ID_CONSOLE_POPFONTCOLOR         2488
#define ID_CONSOLE_COPY                 2491
#define ID_CONSOLE_PASTE                2492
#define ID_PLOT_OPTIONS                 2510
#define ID_PLOT_AUTOSCALE               2511
#define ID_PLOT_TEXTOPTIONS             2512
#define ID_PLOT_ADDDATE                 2513
#define ID_PLOT_ADDERRBARS              2514
#define ID_PLOT_DISPLEGEND              2515
#define ID_PLOT_DISPTITLE               2516
#define ID_PLOT_DISPXTITLE              2517
#define ID_PLOT_DISPYTITLE              2518
#define ID_PLOT_DISPXLABEL              2519
#define ID_PLOT_DISYLABEL               2520
#define ID_PLOT_DISPYLABEL              2521
#define ID_PLOT_SELECTCURVE             2522
#define ID_PLOT_VERTICALBAR             2523
#define ID_PLOT_HORIZONTALBAR           2524
#define ID_PLOT_SYMBOL                  2526
#define ID_PLOT_LINESYMBOL              2527
#define ID_PLOT_COLUMN                  2528
#define ID_PLOT_HBAR                    2529
#define ID_PLOT_INSERTVLINE             2530
#define ID_PLOT_INSERTHLINE             2531
#define ID_PLOT_DUPLICATE               2534
#define ID_PLOT_LINE                    2535
#define ID_PLOT_REPLOT                  2536
#define ID_CURVE_SYMBOLCOLOR            2540
#define ID_CURVE_LINEDOWN               2542
#define ID_CURVE_SYMBOLDOWN             2543
#define ID_CURVE_STYLELINE              2544
#define ID_CURVE_STYLEBOTH              2545
#define ID_CURVE_LINEUP                 2546
#define ID_CURVE_LINECOLOR              2547
#define ID_CURVE_STYLESYMBOL            2548
#define ID_CURVE_SYMBOLUP               2549
#define ID_PLOT_ZOOMIN                  2552
#define ID_PLOT_ZOOMOUT                 2553
#define ID_PLOT_SAVE                    2580
#define ID_PLOT_SAVEAS                  2581
#define ID_IMPORT_ASCII                 2582
#define ID_VIEW_OUTPUT                  2583
#define ID_VIEW_CONSOLE                 2584
#define ID_VIEW_NOTE                    2585
#define ID_VIEW_VIEWPLOT                2586
#define ID_VIEW_PLOT                    2587
#define ID_VIEW_DATA                    2588
#define ID_VIEW_DATAFIT                 2589
#define ID_FITTER_FILTER                2600
#define ID_FITTER_BASELINE              2601
#define ID_FITTER_LINEARFIT             2602
#define ID_FITTER_LINEAR                2603
#define ID_FITTER_NONLINEAR             2604
#define ID_FITTER_PEAK                  2605
#define IDI_RECT1                       2605
#define ID_FITTER_EXPONENTIAL           2606
#define ID_FITTER_LOGARITHMIC           2607
#define ID_FITTER_POWER                 2610
#define ID_FITTER_OPTIONS               2611
#define ID_FITTER_POLYNOMIAL            2612
#define ID_FITTER_SUBSTRACTDATA         2613
#define ID_TOOLBAR                      2640
#define ID_TOOLBAR_PLOT                 2641
#define ID_TOOLBAR_FITTER               2642
#define ID_TOOLBAR_TOOLS                2643
#define ID_FITTER_NOTE                  2802
#define ID_DATA_STATS                   2805
#define ID_DATA_COPY                    2806
#define ID_FITTER_GAUSSIAN              2815
#define ID_FITTER_LORENTZIAN            2816
#define ID_DATA_IMPORTASCII             2818
#define ID_DATA_IMPORT                  2819
#define ID_DATA_IMPORTDLG               2821
#define ID_DATA_OPTIONS                 2826
#define ID_DATA_MASK                    2837
#define ID_DATA_UNMASK                  2838
#define ID_DATA_INVERTMASK              2839
#define ID_DATA_NOTE                    2840
#define ID_DATA_APPENDCOL               2841
#define ID_DATA_INSERTCOL               2842
#define ID_DATA_DELETECOL               2843
#define ID_DATA_INSERTROW               2844
#define ID_DATA_DELETEROW               2845
#define ID_DATA_APPENDROW               2846
#define ID_DATA_CREATESERIES            2847
#define ID_DATA_TRANSPOSE               2848
#define ID_DATA_SORTASC                 2849
#define ID_DATA_SORTDESC                2850
#define ID_DATA_CUT                     2851
#define ID_DATA_PASTE                   2852
#define ID_DATA_SETCOLVAL               2853
#define ID_DATA_PROPERTIES              2854
#define ID_DATA_AUTORESIZE              2855
#define ID_PLOT_ADDLINE                 2866
#define ID_PLOT_ADDRECT                 2867
#define ID_PLOT_ADDELLIPSE              2869
#define ID_PLOT_ADDRECTANGLE            2871
#define ID_ITEM_REMOVE                  2877
#define ID_ITEM_COPY                    2878
#define ID_ITEM_PASTE                   2879
#define ID_PLOT_ADDCURVE                2880
#define ID_DOC_NOTE                     2882
#define ID_EDIT_CELLCOPY                2883
#define ID_EDIT_CELLPASTE               2884
#define ID_HELP_FAQ                     2886
#define ID_HELP_CONSOLE                 2887
#define ID_CURVE_SETACTIVE              2889
#define ID_CURVE_PROPERTIES             2890
#define ID_VIEW_FITREPORT               2891
#define ID_GRAPH_ERRORBARS              2903
#define ID_GRAPH_ERRORBAR               2905
#define ID_FILE_EXPORTG                 2906
#define ID_FILE_EXPORTD                 2907
#define ID_FILE_AUTOEXPORT              2908
#define ID_VIEW_INPUT                   2909
#define ID_TOOLBAR_DATA                 2914
#define ID_TOOLBARS_TOOLS               2915
#define ID_WINDOW_DUP                   2916
#define ID_WINDOW_COPYFORMAT            2917
#define ID_WINDOW_PASTEFORMAT           2918
#define ID_WINDOW_CLOSEALL              2920
#define ID_TOOLBAR_DEVICE               2942
#define ID_FILE_SAVE_NOTE               2944
#define ID_GRAPH_OPTIONS                2948
#define ID_SCRIPT_NEW                   2965
#define ID_SCRIPT_SAVEAS                2966
#define ID_SCRIPT_OPEN                  2967
#define ID_SCRIPT_CLOSE                 2968
#define ID_SCRIPT_RUN                   2969
#define ID_SCRIPT_RUNLINE               2970
#define ID_SCRIPT_RUNTOLINE             2971
#define ID_SCRIPT_RUNTOMARKER           2972
#define ID_SCRIPT_FONT                  2973
#define ID_VIEW_SCRIPT                  2976
#define ID_OUTPUT_CLEAR                 2980
#define ID_EDIT_SELECTALL               2990
#define ID_SCRIPT_SAVE                  2991
#define ID_SCRIPT_RELOAD                2992
#define ID_SCRIPT_LINE                  2993
#define ID_EDIT_GOTO                    2994
#define ID_ANALYSIS_DIFF                3009
#define ID_ANALYSIS_INTEGRATE           3010
#define ID_ANALYSIS_AVERAGE             3011
#define ID_SCRIPT_FAVORITE              3014
#define ID_FAVORITE_ONE                 3020
#define ID_FAVORITE_TWO                 3021
#define ID_FAVORITE_THREE               3022
#define ID_FAVORITE_FOUR                3023
#define ID_SCRIPT_RESET                 3028
#define ID_PLOT_TEMPLATES               3031
#define ID_PLOT_MASKTO                  3033
#define ID_PLOT_MASKFROM                3034
#define ID_PLOT_UNMASK                  3035
#define ID_ANALYSIS_FFT                 3037
#define ID_ANALYSIS_AUTOCORR            3038
#define ID_TOOLBAR_MAIN                 3040
#define ID_TOOLBAR_DATASHEET            3041
#define ID_VIEW_TOOLBAR_DATA            3042
#define ID_VIEW_TOOLBAR_PLOT            3043
#define ID_VIEW_STATUSBAR               3044
#define ID_GRAPH_ADDHORIZ               3051
#define ID_PLOT_ADDHLINE                3052
#define ID_PLOT_ADDVLINE                3053
#define ID_VIEW_VARLIST                 3055
#define ID_HELP_CONTENTS                3200
#define ID_HELP_CONTENTS_PDF            3201
#define ID_SCRIPT_ADDMARKER             3300
#define ID_SCRIPT_NEXTMARKER            3302
#define ID_SCRIPT_PREVMARKER            3303
#define ID_SCRIPT_LINENUMBERS           3304
#define ID_SCRIPT_SYNTAX                3305
#define ID_SCRIPT_COLORS                3306
#define ID_SCRIPT_COLOR_DEF             3307
#define ID_SCRIPT_COLOR_KEY             3308
#define ID_SCRIPT_COLOR_STR             3309
#define ID_SCRIPT_COLOR_COM             3310
#define ID_SCRIPT_COLOR_NUM             3311
#define ID_SCRIPT_COLOR_LIB             3312
#define ID_SCRIPT_COLOR_LINENUM         3313
#define IDK_SCRIPT_FONTSTYLE_DEF        3314
#define IDK_SCRIPT_FONTSTYLE_KEY        3315
#define IDK_SCRIPT_FONTSTYLE_STR        3316
#define IDK_SCRIPT_FONTSTYLE_COM        3317
#define IDK_SCRIPT_FONTSTYLE_NUM        3318
#define IDK_SCRIPT_FONTSTYLE_LIB        3319
#define IDK_SCRIPT_FONTSTYLE_LINENUM    3320
#define IDL_SCRIPT_FONTSTYLE_DEF        3321
#define IDL_SCRIPT_FONTSTYLE_KEY        3322
#define IDL_SCRIPT_FONTSTYLE_STR        3323
#define IDL_SCRIPT_FONTSTYLE_COM        3324
#define IDL_SCRIPT_FONTSTYLE_NUM        3325
#define IDL_SCRIPT_FONTSTYLE_LIB        3326
#define IDL_SCRIPT_FONTSTYLE_LINENUM    3327
#define ID_SCRIPT_LINESPACING_100       3340
#define ID_SCRIPT_LINESPACING_125       3341
#define ID_SCRIPT_LINESPACING_150       3342
#define ID_SCRIPT_LINESPACING_175       3343
#define ID_SCRIPT_ZOOMIN                3350
#define ID_SCRIPT_ZOOMOUT               3351
#define ID_SCRIPT_ZOOMNONE              3352
#define ID_SCRIPT_DELETEALLMARKERS      3360
#define ID_SCRIPT_CLEAROUTPUT           3370
#define ID_SCRIPT_OUTPUTSIZE_SMALL      3371
#define ID_SCRIPT_OUTPUTSIZE_MEDIUM     3372
#define ID_SCRIPT_OUTPUTSIZE_LARGE      3373
#define ID_SCRIPT_OUTPUT_VIEW           3374
#define ID_SCRIPT_AUTOCOMPLETE          3375
#define ID_SCRIPT_SAMPLE01              3380
#define ID_SCRIPT_SAMPLE02              3381
#define ID_SCRIPT_SAMPLE03              3383
#define ID_SCRIPT_SAMPLE04              3384
#define IDC_REGULAR_EXPRESSION          3999

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        372
#define _APS_NEXT_COMMAND_VALUE         3063
#define _APS_NEXT_CONTROL_VALUE         1962
#define _APS_NEXT_SYMED_VALUE           460
#endif
#endif
